---

- name: remove knative serving installation
  when: openshift_serverless_install_serving | default(False) | bool
  k8s:
    state: absent
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeServing
    name: knative-serving
    namespace: knative-serving
  ignore_errors: true

- name: remove knative eventing installation
  when: openshift_serverless_install_serving | default(False) | bool
  k8s:
    state: absent
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeEventing
    name: knative-eventing
    namespace: knative-eventing
  ignore_errors: true

- name: wait until all knative serving pods have been removed
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: knative-serving
    field_selectors:
    - status.phase=Running
  register: r_serving_pods
  retries: 20
  delay: 5
  until: r_serving_pods.resources | length == 0

- name: wait until all knative eventing pods have been removed
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: knative-eventing
    field_selectors:
    - status.phase=Running
  register: r_eventing_pods
  retries: 20
  delay: 5
  until: r_eventing_pods.resources | length == 0

- name: get installed csv
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ openshift_serverless_subscription_name }}"
    namespace: "{{ openshift_serverless_subscription_namespace }}"
  register: r_subscription

- name: remove csv
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "{{ openshift_serverless_subscription_namespace }}"
  when:
  - r_subscription.resources | length > 0
  - r_subscription.resources[0].status.currentCSV is defined
  - r_subscription.resources[0].status.currentCSV | length > 0

- name: remove subscription
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ openshift_serverless_subscription_name }}"
    namespace: "{{ openshift_serverless_subscription_namespace }}"

- name: remove knative-serving and knative-eventing projects
  k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ item }}"
  loop:
  - knative-serving
  - knative-eventing

- name: remove serverless crds
  k8s:
    state: absent
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
  - knativeservings.operator.knative.dev
  - knativeeventings.operator.knative.dev
  - apiserversources.sources.knative.dev
  - brokers.eventing.knative.dev
  - certificates.networking.internal.knative.dev
  - channels.messaging.knative.dev
  - configurations.serving.knative.dev
  - containersources.sources.knative.dev
  - eventtypes.eventing.knative.dev
  - images.caching.internal.knative.dev
  - ingresses.networking.internal.knative.dev
  - inmemorychannels.messaging.knative.dev
  - metrics.autoscaling.internal.knative.dev
  - parallels.flows.knative.dev
  - pingsources.sources.knative.dev
  - podautoscalers.autoscaling.internal.knative.dev
  - revisions.serving.knative.dev
  - routes.serving.knative.dev
  - sequences.flows.knative.dev
  - serverlessservices.networking.internal.knative.dev
  - services.serving.knative.dev
  - sinkbindings.sources.knative.dev
  - subscriptions.messaging.knative.dev
  - triggers.eventing.knative.dev

- name: find installplans
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: "{{ openshift_serverless_subscription_namespace }}"
  register: r_install_plans

- name: set installplan name
  when: r_install_plans.resources | length > 0
  set_fact:
    openshift_serverless_install_plan: "{{ r_install_plans.resources | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'serverless-operator')].metadata.name|[0]

- name: remove installplan
  when:
  - openshift_serverless_install_plan is defined
  - openshift_serverless_install_plan |default("") | length > 0
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ openshift_serverless_install_plan }}"
    namespace: "{{ openshift_serverless_subscription_namespace }}"