---

- name: "get operatorgroups in {{ operatorgroup_namespace }}"
  k8s_info:
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    namespace: "{{ operatorgroup_namespace }}"
  register: r_operatorgroup

- name: "create operator group in {{ operatorgroup_namespace }}"
  k8s:
    state: present
    namespace: "{{ operatorgroup_namespace }}"
    definition: "{{ lookup('template', resource ) | from_yaml }}"
  vars:
    resource: "templates/operatorgroup.j2"
  when: r_operatorgroup.resources | length == 0
