---
- name: "get rh-sso admin token"
  include_tasks: admin_token.yml

- name: "Create realms"
  include_tasks: realm.yml
  loop: "{{ range(realm_first|int, realm_last|int + 1, 1)|list }}"
  when: realm_last|int > 0
  vars:
    realm_id: "{{ realm_base_name }}{{ item }}"
