---

- name: "copy realm template for realm {{ realm_id }}"
  template:
    src: "{{ resources_dir }}/{{ realm_template }}"
    dest: "{{ work_dir }}/{{ realm_id }}.json"

- name: "check if {{ realm_id }} exists"
  uri:
    url: "{{ rhsso_url }}/auth/admin/realms/{{ realm_id }}"
    method: GET
    headers:
      Authorization: Bearer {{ admin_token }}
    status_code: 200,404
    validate_certs: no
  register: r_realm_result
  changed_when: false

- name: "create {{ realm_id }} realm"
  uri:
    url: "{{ rhsso_url }}/auth/admin/realms"
    method: POST
    headers:
      Authorization: Bearer {{ admin_token }}
      Content-Type: application/json
    body: "{{ lookup('file', work_dir + '/' + realm_id + '.json') }}"
    body_format: json
    status_code: 201
    validate_certs: no
  when: r_realm_result.status == 404
