---

- name: get packagemanifest for openshift pipelines operator
  k8s_info:
    api_version: packages.operators.coreos.com/v1
    kind: PackageManifest
    name: "{{ openshift_pipelines_packagemanifest }}"
    namespace: openshift-marketplace
  register: r_packagemanifest

- name: set facts for openshift pipelines operator
  set_fact:
    openshift_pipelines_subscription_package_name: "{{ r_packagemanifest.resources[0].status.packageName }}"
    openshift_pipelines_subscription_catalog_source: "{{ r_packagemanifest.resources[0].status.catalogSource }}"
    openshift_pipelines_subscription_catalog_source_namespace: "{{ r_packagemanifest.resources[0].status.catalogSourceNamespace }}"

- name: determine channel for openshift pipelines operator if no channel specified
  when: openshift_pipelines_subscription_channel | default("") | length == 0
  set_fact:
    openshift_pipelines_subscription_channel: "{{ r_packagemanifest.resources[0].status.defaultChannel }}"

- name: print openshift pipelines channel to be installed
  debug:
    msg: "OpenShift Pipelines operator channel to be installed: {{ openshift_pipelines_subscription_channel }}"

- name: "create subscription for openshift pipelines operator in {{ openshift_pipelines_subscription_namespace }}"
  k8s:
    state: present
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
    definition: "{{ lookup('template', resource) | from_yaml }}"
  vars:
    resource: "{{ resources_dir }}/subscription.j2"

- name: wait until installplan is created
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
  register: r_install_plan
  retries: 30
  delay: 5
  until:
    - r_install_plan.resources | length > 0
    - r_install_plan.resources[0] | to_json | from_json | json_query(query) | length > 0
  vars:
    query: "spec.clusterServiceVersionNames[] | [?contains(@, 'openshift-pipelines-operator') == `true`]"

- name: manually approve installplan
  when: not openshift_pipelines_automatic_installplan_approval
  block:
    - name: set installplan name
      set_fact:
        openshift_pipelines_install_plan: >-
          {{ r_install_plan.resources | to_json | from_json | json_query(query) }}
      vars:
        query: >-
          [?starts_with(spec.clusterServiceVersionNames[0], 'openshift-pipelines-operator')].metadata.name|[0]

    - name: approve installplan
      k8s:
        state: present
        namespace: "{{ openshift_pipelines_subscription_namespace }}"
        definition: "{{ lookup( 'template', resource ) }}"
      vars:
        resource: "{{ resources_dir }}/installplan.j2"
        install_plan_name: "{{ openshift_pipelines_install_plan }}"

- name: get installed csv
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ openshift_pipelines_subscription_name }}"
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
  register: r_subscription
  retries: 30
  delay: 5
  until:
  - r_subscription.resources[0].status.currentCSV is defined
  - r_subscription.resources[0].status.currentCSV | length > 0

- name: wait until csv is installed
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
  register: r_csv
  retries: 15
  delay: 5
  until:
  - r_csv.resources[0].status.phase is defined
  - r_csv.resources[0].status.phase | length > 0
  - r_csv.resources[0].status.phase == "Succeeded"

- name: wait until pipelines pods are ready
  k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ openshift_pipelines_deployment_namespace }}"
    name: "{{ openshift_pipelines_deployment_name }}"
  register: r_pipeline_controller_deployment
  retries: 30
  delay: 10
  until:
  - r_pipeline_controller_deployment.resources | length | int > 0
  - r_pipeline_controller_deployment.resources[0].status.readyReplicas is defined
  - r_pipeline_controller_deployment.resources[0].status.readyReplicas | int == r_pipeline_controller_deployment.resources[0].spec.replicas | int
