---

- name: remove openshift pipelines installation
  k8s:
    state: absent
    api_version: operator.tekton.dev/v1alpha1
    kind: Config
    name: cluster
  ignore_errors: true

- name: wait until all openshift pipelines pods have been removed
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ openshift_pipelines_deployment_namespace }}"
  register: r_pipelines_pods
  retries: 20
  delay: 5
  until: r_pipelines_pods.resources | length == 0

- name: get installed csv
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ openshift_pipelines_subscription_name }}"
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
  register: r_subscription

- name: remove csv
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
  when:
  - r_subscription.resources | length > 0
  - r_subscription.resources[0].status.currentCSV is defined
  - r_subscription.resources[0].status.currentCSV | length > 0

- name: remove subscription
  k8s:
    state: absent
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
    definition: "{{ lookup('template', resource ) | from_yaml }}"
  vars:
    resource: "{{ resources_dir }}/subscription.j2"

- name: remove {{ openshift_pipelines_deployment_namespace }} project
  k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ openshift_pipelines_deployment_namespace }}"

- name: remove tekton crds
  k8s:
    state: absent
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: config.operator.tekton.dev

- name: find installplans
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: "{{ openshift_pipelines_subscription_namespace }}"
  register: r_install_plans

- name: set installplan name
  when: r_install_plans.resources | length > 0
  set_fact:
    openshift_pipelines_install_plan: "{{ r_install_plans.resources | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'openshift-pipelines-operator')].metadata.name|[0]

- name: remove installplan
  when:
  - openshift_pipelines_install_plan is defined
  - openshift_pipelines_install_plan |default("") | length > 0
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ openshift_pipelines_install_plan }}"
    namespace: "{{ openshift_pipelines_subscription_namespace }}"