---

- name: Deploy Red Hat SSO
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/rhsso.yml

  tasks:
    - set_fact:
        work_dir_name: rhsso
    - include_role:
        name: ../roles/rhsso
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/rhsso
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
    - include_role:
        name: ../roles/rhsso
        tasks_from: create_realms
      when: >
        ACTION is defined and
        ACTION|trim() == "create_realms"
