---

- name: remove the tenants
  when: threescale_create_tenants is true
  include_tasks: 
      file: uninstall_tenants.yml
  loop: "{{ range(threescale_start_tenant, threescale_end_tenant|int + 1, 1)|list }}"

- name: "delete 3scale api manager"
  k8s:
    state: absent
    api_version: apps.3scale.net/v1alpha1
    kind: APIManager
    namespace: "{{ threescale_namespace }}"
    name: "{{ threescale_api_manager_name }}"

- name: "delete system storage pvc"
  k8s:
    state: absent
    api_version: v1
    kind: pvc
    namespace: "{{ threescale_namespace }}"
    name: system-storage

- name: "delete image pull secret"
  k8s:
    state: absent
    api_version: v1
    kind: secret
    namespace: "{{ threescale_namespace }}"
    name: threescale-registry-auth

- name: "delete system-smtp secret"
  k8s:
    state: absent
    api_version: v1
    kind: secret
    namespace: "{{ threescale_namespace }}"
    name: system-smtp

- name: "delete aws-auth secret"
  k8s:
    state: absent
    api_version: v1
    kind: secret
    namespace: "{{ threescale_namespace }}"
    name: "{{ threescale_object_storage_secret }}"

- name: "delete 3scale operator in {{ threescale_namespace }}"
  import_role:
    name: openshift_operator
    tasks_from: uninstall
  vars:
    operator_name: 3scale-operator
    subscription_namespace: "{{ threescale_subscription_namespace }}" 
    subscription_name: "{{ threescale_subscription_name }}"
    csv_prefix: "{{ threescale_csv_prefix }}"

- name: "remove operatorgroup"
  when: threescale_remove_operator_group | default(False) | bool
  k8s:
    state: absent
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    name: "{{ threescale_operatorgroup }}"
    namespace: "{{ threescale_namespace }}"

- name: "remove threescale crds"
  when: threescale_remove_cluster_resources | default(False) | bool
  k8s:
    state: absent
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
  - "apimanagerbackups.apps.3scale.net"
  - "apimanagerrestores.apps.3scale.net"
  - "apimanagers.apps.3scale.net"
  - "backends.capabilities.3scale.net"
  - "products.capabilities.3scale.net"
  - "tenants.capabilities.3scale.net"
