---

- name: "wait until kafka-cluster-entity-operator is active in {{ kafka_cluster_namespace }}"
  k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ kafka_cluster_namespace }}"
    name: "{{ entity_operator_deployment }}"
  register: r_kafka_cluster_entity_operator
  retries: 50
  delay: 10
  until:
  - r_kafka_cluster_entity_operator.resources is defined
  - r_kafka_cluster_entity_operator.resources | length | int > 0
  - r_kafka_cluster_entity_operator.resources[0].status.availableReplicas is defined
  - r_kafka_cluster_entity_operator.resources[0].status.availableReplicas | int == r_kafka_cluster_entity_operator.resources[0].spec.replicas | int

- name: "create kafka topic"
  k8s:
    state: present
    namespace: "{{ kafka_cluster_namespace }}"
    definition: "{{ lookup('template', resource ) | from_yaml }}"
  vars:
    resource: "{{ resources_dir }}/kafka-topic.j2" 