---

- name: "create cloud services api access token secret"
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', resource ) | from_yaml }}"
  vars:
    resource: "templates/cloud-services-api-access-token-secret.j2"
