---

- name: "create cloud services service account secret"
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', resource ) | from_yaml }}"
  vars:
    resource: "templates/cloud-services-service-account-secret.j2"
