---

- name: remove argocd installation
  k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: ArgoCD
    name: "{{ argocd_cr_name }}"
    namespace: "{{ argocd_namespace }}"
  ignore_errors: true

- name: get installed csv
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ argocd_subscription_name }}"
    namespace: "{{ argocd_subscription_namespace }}"
  register: r_subscription

- name: remove csv
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ r_subscription.resources[0].status.currentCSV }}"
    namespace: "{{ argocd_subscription_namespace }}"
  when:
  - r_subscription.resources | length > 0
  - r_subscription.resources[0].status.currentCSV is defined
  - r_subscription.resources[0].status.currentCSV | length > 0

- name: remove subscription
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ argocd_subscription_name }}"
    namespace: "{{ argocd_subscription_namespace }}"

- name: find installplans
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    namespace: "{{ argocd_subscription_namespace }}"
  register: r_install_plans

- name: set installplan name
  when: r_install_plans.resources | length > 0
  set_fact:
    argocd_install_plan: "{{ r_install_plans.resources | to_json | from_json | json_query(query) }}"
  vars:
    query: >-
      [?starts_with(spec.clusterServiceVersionNames[0], 'argocd-operator')].metadata.name|[0]

- name: remove installplan
  when:
  - argocd_install_plan is defined
  - argocd_install_plan | default("") | length > 0
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: "{{ argocd_install_plan }}"
    namespace: "{{ argocd_subscription_namespace }}"

- name: remove operatorgroup
  when: argocd_remove_operator_group | default(False) | bool
  k8s:
    state: absent
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    name: "{{ argocd_operator_group }}"
    namespace: "{{ argocd_namespace }}"

- name: remove argocd crds
  k8s:
    state: absent
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
  - "applications.argoproj.io"
  - "appprojects.argoproj.io"
  - "argocdexports.argoproj.io"
  - "argocds.argoproj.io"
