---

- name: "delete kafka topics"
  import_role:
    name: kafka_topic
    tasks_from: uninstall

- name: "remove {{ kafka_cluster }} kafka cluster"
  k8s:
    state: absent
    api_version: kafka.strimzi.io/v1beta1
    kind: Kafka
    namespace: "{{ kafka_cluster_namespace }}"
    name: "{{ kafka_cluster }}"
