---

- name: "delete kafka topics"
  import_role:
    name: kafka_topic
    tasks_from: uninstall

- name: "remove metrics configmaps"
  k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    namespace: "{{ kafka_cluster_namespace }}"
    name: "{{ item }}"
  loop:
    - "{{ kafka_configmap_metrics }}"
    - "{{ zookeeper_configmap_metrics }}"

- name: "remove {{ kafka_cluster }} kafka cluster"
  k8s:
    state: absent
    api_version: "{{ kafka_cr_api_version }}"
    kind: Kafka
    namespace: "{{ kafka_cluster_namespace }}"
    name: "{{ kafka_cluster }}"
