---

- name: Deploy Kafka Topic
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/strimzi.yml

  tasks:
    - include_role:
        name: ../roles/kafka_topic
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "create"
    - include_role:
        name: ../roles/kafka_topic
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"