---

- name: Install Kafdrop
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - include_role:
        name: ../roles/kafdrop
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/kafdrop
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
