---

topic_name: topic-test

topic_partitions: 15
topic_replicas: 3

topic_retention_ms: -1
topic_config_segment_bytes: 1073741824 # 1 Gigibyte
topic_config_message_timestamp_type: CreateTime
topic_config_cleanup_policy: compact
