---

- name: Deploy Argo CD Operator
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/argocd.yml

  tasks:
    - include_role:
        name: ../roles/argocd
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/argocd
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"